import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import dayjs from 'dayjs'
import { useRecoilState } from 'recoil'
import timezone from 'dayjs/plugin/timezone'
import Skeleton from 'react-loading-skeleton'; 

import Card from '@/components/Card'

import { getPosts } from '@/services/posts'
import { getAuthors } from '@/services/authors'
import {loading} from '@/store/loading'

import 'react-loading-skeleton/dist/skeleton.css'

dayjs.extend(timezone)


interface Authors {
  id:number;
  avatar_url: string;
  name:string;
  place:string;
  role:string;
}

interface Posts {
  id:number
  author_id:number;
  title: string;
  body: string;
  image_url: string;
  created_at: string;
}


const Home: NextPage = () => {

  const [posts, setPosts] = useState([])

  const [isLoading, setIsLoading] = useRecoilState(loading);


  useEffect(() => {
   (async()=>{
    let timer: any;
    setIsLoading(true);
     try {
        const res= await getAuthors()
        if(res.status === 200&& res.statusText === 'OK') {
          try {
            const response= await getPosts()
            if(response.status === 200 && response.statusText === 'OK'){
              const newPosts = response.data.map((i:Posts) => {
                const author = res.data.find((item:Authors) => item.id === i.author_id)
                return {...i, name:author.name, avatar_url:author.avatar_url }
              })
              setPosts(newPosts)
              timer = setTimeout(() => {
                setIsLoading(false);
              }, 2000);

            }
          } catch (error) {
            timer = setTimeout(() => {
              setIsLoading(false);
            }, 2000);
          }
        }
     } catch (error) {
      timer = setTimeout(() => {
        setIsLoading(false);
      }, 2000);
     }
      return () => {
        clearTimeout(timer);
      };
   })()
}, []);

  return (
    <div className='py-10'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' w-full h-full'>
        <h1 className='text-3xl font-bold'>MAQE FORUM</h1>
        <p className='text-gray-800 mb-5 mt-10'>Your current timezone is: {dayjs.tz.guess()}</p>
        <div className='grid grid-cols-1 gap-5'>
          {isLoading ? (
            <>
              <div  className='p-5 bg-white h-72 flex'>
                <div>
                  <Skeleton height={208} width={240} />
                </div>
                <div className='w-2/3 ml-5'>
                  <Skeleton  height={30} />
                  <Skeleton count={3} height={18} />
                </div>
              </div>
              <div  className='p-5 bg-white h-72 flex'>
                <div>
                  <Skeleton height={208} width={240} />
                </div>
                <div className='w-2/3 ml-5'>
                  <Skeleton  height={30} />
                  <Skeleton count={3} height={18} />
                </div>
              </div>
            </>
          ): 
          posts.map((item:any) => (
            <Card key={item.id} item={item}/>
          ))
          }

       
        </div>
      </main>
      
      

     
    </div>
  )
}

export default Home
